stages:
  - checkstyle
  - test
  - build

checkstyle:
  image: maven:latest
  script:
    - mvn checkstyle:checkstyle
test:
  stage: test
  image: maven:latest
  script:
    - mvn verify
build:
  stage: build
  image: maven:latest
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar